### ISSUE TITLE
Tracks with muxed Audio/Video not supported

### ISSUE THREAD

**Issue by AxelDelmas** [castlabs/dashas#33]
This case is handled by SegmentHandler.validateTracksNumber and an exception is thrown, but do you plan to add suport any time soon?

**Comment by tomasz-oponowicz** [comment]
Muxed media tracks aren't allowed in DASH.

**Comment by tomasz-oponowicz** [comment]
Sorry, it's supported by DASH specification. However we don't plan to support it in the recent future.

**Comment by tomasz-oponowicz** [comment]
Hi AxelDelmas,

If you wish to have further discussion on the features, we can provide
consultant service via commercial process, please contact:

sales@castlabs.com

Best regards,
Tomasz Oponowicz
