### ISSUE TITLE
manifest with longer audio duration stops when video tracks complete

### ISSUE THREAD

**Issue by gberkman** [castlabs/dashas#34]
Hi,
as seen in the url http://10.0.0.28/videos/8115637/Manifest.mpd audio tracks are longer than video tracks. Last 10 seconds there is only audio (still video image). But, altough manifest duration (that is audio duration) is 01:48, stream stops playing at 01:39 (when video tracks complete). I think need a flag addition for longer audio tracks (for example like silent audio).

**Comment by tomasz-oponowicz** [comment]
Can't reach specified URL...

However it's possible because for the sake of simplicity everything is synchronised around a video timeline...
