### ISSUE TITLE
LC AAC audio is not playing

### ISSUE THREAD

**Issue by pratikpradhan** [castlabs/dashas#39]
We have audio and video segments separated. We tried with audio fragments having LC AAC audio but its not playing.

Can you help?

**Comment by chartelt** [comment]
Can you share the manifest file and or public Link to it?

**Comment by pratikpradhan** [comment]
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500000S" type="static" mediaPresentationDuration="PT0H1M52.73S" profiles="urn:mpeg:dash:profile:full:2011">
<ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
<Title>gca_dash.mpd generated by GPAC</Title>
</ProgramInformation>
<Period duration="PT0H1M52.73S">
<AdaptationSet segmentAlignment="true" lang="und">
<Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="44100" startWithSAP="1" bandwidth="159280">
<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
<SegmentList timescale="44100" duration="216139">
<Initialization sourceURL="audio-fraginit.mp4"/>
<SegmentURL media="audio-frag1.m4s"/>
<SegmentURL media="audio-frag2.m4s"/>
<SegmentURL media="audio-frag3.m4s"/>
<SegmentURL media="audio-frag4.m4s"/>
<SegmentURL media="audio-frag5.m4s"/>
<SegmentURL media="audio-frag6.m4s"/>
<SegmentURL media="audio-frag7.m4s"/>
<SegmentURL media="audio-frag8.m4s"/>
<SegmentURL media="audio-frag9.m4s"/>
<SegmentURL media="audio-frag10.m4s"/>
<SegmentURL media="audio-frag11.m4s"/>
<SegmentURL media="audio-frag12.m4s"/>
<SegmentURL media="audio-frag13.m4s"/>
<SegmentURL media="audio-frag14.m4s"/>
<SegmentURL media="audio-frag15.m4s"/>
<SegmentURL media="audio-frag16.m4s"/>
<SegmentURL media="audio-frag17.m4s"/>
<SegmentURL media="audio-frag18.m4s"/>
<SegmentURL media="audio-frag19.m4s"/>
<SegmentURL media="audio-frag20.m4s"/>
<SegmentURL media="audio-frag21.m4s"/>
<SegmentURL media="audio-frag22.m4s"/>
<SegmentURL media="audio-frag23.m4s"/>
</SegmentList>
</Representation>
</AdaptationSet>
</Period>
</MPD>

**Comment by pratikpradhan** [comment]
```
<!--
 MPD file Generated with GPAC version 0.5.1-DEV-rev6273  on 2015-07-14T10:44:18Z
-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500000S" type="static" mediaPresentationDuration="PT0H1M52.73S" profiles="urn:mpeg:dash:profile:full:2011">
<ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
<Title>gca_dash.mpd generated by GPAC</Title>
</ProgramInformation>
<Period duration="PT0H1M52.73S">
<AdaptationSet segmentAlignment="true" lang="und">
<Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="44100" startWithSAP="1" bandwidth="159280">
<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
<SegmentList timescale="44100" duration="216139">
<Initialization sourceURL="audio-fraginit.mp4"/>
<SegmentURL media="audio-frag1.m4s"/>
<SegmentURL media="audio-frag2.m4s"/>
<SegmentURL media="audio-frag3.m4s"/>
<SegmentURL media="audio-frag4.m4s"/>
<SegmentURL media="audio-frag5.m4s"/>
<SegmentURL media="audio-frag6.m4s"/>
<SegmentURL media="audio-frag7.m4s"/>
<SegmentURL media="audio-frag8.m4s"/>
<SegmentURL media="audio-frag9.m4s"/>
<SegmentURL media="audio-frag10.m4s"/>
<SegmentURL media="audio-frag11.m4s"/>
<SegmentURL media="audio-frag12.m4s"/>
<SegmentURL media="audio-frag13.m4s"/>
<SegmentURL media="audio-frag14.m4s"/>
<SegmentURL media="audio-frag15.m4s"/>
<SegmentURL media="audio-frag16.m4s"/>
<SegmentURL media="audio-frag17.m4s"/>
<SegmentURL media="audio-frag18.m4s"/>
<SegmentURL media="audio-frag19.m4s"/>
<SegmentURL media="audio-frag20.m4s"/>
<SegmentURL media="audio-frag21.m4s"/>
<SegmentURL media="audio-frag22.m4s"/>
<SegmentURL media="audio-frag23.m4s"/>
</SegmentList>
</Representation>
</AdaptationSet>
</Period>
</MPD>

```

**Comment by chartelt** [comment]
Unfortunately Audio-only DASH is not supported in the open-source version.
