### ISSUE TITLE
dashas.castlabs.com DNS entry is unreachable 

### ISSUE THREAD

**Issue by vkp123** [castlabs/dashas#45]
I am trying to start development with **dashas** project . I couldn't reach  _dashas.castlabs.com_ DNS entry while building the source code (For example : http://dashas.castlabs.com/ivy/apache-flex-sdk-4.12.1.xml ) . I am trying to build the project on Ubuntu 17.04 with Gradle 1.1 . I want to know when DNS entry will be reachable or maybe can you suggest any different source to download this dependency . Please solve this issue . I am stuck in the middle .

**Comment by tomasz-oponowicz** [comment]
Thx for a bug report. 

Can you try again? We fixed the DNS record.

**Comment by vkp123** [comment]
Thanks for your quick support . It is working now . I have closed the issue .
